# Pomi?dzy .net/ a ? dopisz nazw? bazy danych
spring.data.mongodb.uri=mongodb+srv://Rentier123:BeautifulPassword23@cluster0.0g3nfq6.mongodb.net/OptionStrategyDB?&appName=Cluster0

# To zostaje bez zmian
alphavantage.api.key=R875E3J67YS7G93Salphavantage.api.key=R875E3J67YS7G93S